name: C
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Boehm GC
      run: sudo apt-get install -y libgc-dev
    - name: make
      run: make
    - name: make test
      run: make test
